### ISSUE TITLE
Logs are not saved in the blob storage - how to troubleshoot the issue?

### ISSUE THREAD

**Issue by JocaPC** [JDetmar/NLog.Extensions.AzureStorage#16]
I think that I have done everything that you described but still I'm getting no logs in Azure Blob Storage. Logging to file works fine, but when I switch target to Azure blob storage nothing happens. How can I troubleshoot the issue?

I'm using ASP.NET Core 2.1 with the following packages:
```
<PackageReference Include="NLog" Version="4.5.10" />
<PackageReference Include="NLog.Extensions.AzureStorage" Version="1.0.9" />
<PackageReference Include="NLog.Web.AspNetCore" Version="4.7.0" />
```

Content of nlog.config is:
```
<target xsi:type="AzureBlobStorage"
            name="BlobStorage"
            blobName="${shortdate}.log"
            layout="${longdate:universalTime=true} ${level:uppercase=true} - ${logger}: ${message} ${exception:format=tostring:innerFormat=tostring:maxInnerExceptionLevel=1000}"
            container="logs"
             connectionString="DefaultEndpointsProtocol=https;AccountName=********;AccountKey=Z9******GpA==;EndpointSuffix=core.windows.net"
            />
```
I have a single rule in nlog.config:
```
  <rules>
   <logger name="*" minlevel="Trace" writeTo="BlobStorage" />
  </rules>

```
The connection string is copied from the portal: Settings/Access keys/Connection string, and container is valid (I already have one file in the container).

Properties of my Azure Storage are (from the portal):
```
Performance/Access tier
Standard/Hot
Replication
Locally-redundant storage (LRS)
Account kind
StorageV2 (general purpose v2)
```

If I'm not missing something how can I troubleshoot the issue? I configured NLog to throw exceptions if needed, but nothing is reported:

```
            //add NLog to ASP.NET Core
            loggerFactory.AddNLog();
            NLog.LogManager.ThrowExceptions = true;
            NLog.LogManager.ThrowConfigExceptions = true;
```

Is this extension supported in dotnet core 2.1 `<TargetFrameworks>netcoreapp2.1</TargetFrameworks>` ?

**Comment by snakefoot** [comment]
Ensure **Copy to Output Directory**=Preserve Newest for NLog.config.

Have you checked https://github.com/NLog/NLog/wiki/Internal-Logging to see if NLog.config is loaded properly, and loggers matches the rules ?

**Comment by snakefoot** [comment]
Try add this target-assembly to the extensions-section of your nlog.config<http://nlog.config>

Sent from my Sony Xperia


---- Jovan Popovic wrote ----


Thank you for the hint I have found the error, but unfortunatelly I still don't understand the cause. internal log reports that it cannot find the target AzureBlobStorage and that maybe XML is invalid:

2018-10-03 11:06:22.9260 Error Parsing configuration from D:\Data\Documents\GitHub\sql-server-samples\samples\demos\belgrade-product-catalog-demo\nlog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing D:\Data\Documents\GitHub\sql-server-samples\samples\demos\belgrade-product-catalog-demo\nlog.config.  ---> System.ArgumentException: Target cannot be found: 'AzureBlobStorage'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2018-10-03 11:06:22.9260 Warn Failed loading config from D:\Data\Documents\GitHub\sql-server-samples\samples\demos\belgrade-product-catalog-demo\nlog.config. Invalid XML?


The content of nlog.config is valid XML (I checked this). So I'm not sure is there some other attribute that I missed. I have even replaced data in connection string with *** to avoid some special character that might be copied from Azure portal, but still it cannot load it.
Here is the content of my nlog.config:

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile=".\internal-nlog.txt">

  
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  
  <targets>
    <target xsi:type="AzureBlobStorage"
            name="AzureBlobStorage"
            blobName="shortdate.log"
            layout="${message}"
            container="logs"
            connectionString="DefaultEndpointsProtocol=https;AccountName=***;AccountKey=i***=;EndpointSuffix=core.windows.net"
            />
  </targets>

  
  <rules>
    <logger name="*" minlevel="Trace" writeTo="AzureBlobStorage" />
  </rules>
</nlog>


In this case I would expect to fail to write to blob storage because I placed fake connection string, but it cannot even initialize AzureBlobStorage target. Can I somewhere validate that this extension is loaded and recognized by NLog?

**Comment by JocaPC** [comment]
This solved the issue. I have added the following node in nlog.config:

```
  <extensions>
    <add assembly="NLog.Extensions.AzureStorage"/>
  </extensions>
```

Thanks for help.

**Comment by snakefoot** [comment]
@JocaPC Saw your blog-post on twitter:

https://medium.com/@jocapc/configuring-nlog-in-asp-net-core-web-app-59d1ab3697de

You should not use both `UseNLog` (new style) and `AddNLog` (old style) together.

See `Program.cs` example here: 

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2#4-update-programcs

**Comment by JocaPC** [comment]
Thanks, I will update the post.

**Comment by snakefoot** [comment]
@JocaPC Please also remove any advice about using `NLog.LogManager.ThrowExceptions = true`. It is only intended for unit-testing, and will give a lot of unwanted side-effects.

It is a good idea to have `ThrowConfigExceptions` but instead of configuring it by code, then you can add it to the nlog.config:

`<nlog autoReload="true" throwConfigExceptions="true">`

**Comment by snakefoot** [comment]
@JocaPC Polite poke. Please remove these lines from your guide for changing `Startup.cs`:

```
      NLog.LogManager.ThrowExceptions = true;
      NLog.LogManager.ThrowConfigExceptions = true;        
```

And instead recommend adding `throwConfigExceptions="true"` to NLog.config.
