### ISSUE TITLE
BlobStorageTarget not working after configuration reload

### ISSUE THREAD

**Issue by oIllenseer** [JDetmar/NLog.Extensions.AzureStorage#31]
We implemented the NLog with AzureStorage successfully. As we go to azure Web Application with it we notice issues in loading the correct configuration. For that we need to reload the configuration and in this case the BlobStorageTarget is not writing files on storage anymore.

see: [${configsetting} is not correct replaced in Azure App Service with .NET Core 2.2](https://github.com/NLog/NLog/issues/3171)

**Comment by snakefoot** [comment]
Your trust in random people solving your environment problems is admirable.

You have confirmed that the blob-target is working for you in one environment.

You have confirmed that the blob-target fails to initialize probably in an other environment, without first having performed secondary config-reload after having setup the configuration correctly.

Think you have to figure yourself why the other environment is not working. Maybe make a custom build of the blob-target with extra debug logging.

**Comment by oIllenseer** [comment]
> Your trust in random people solving your environment problems is admirable.
> 
> You have confirmed that the blob-target is working for you in one environment.
> 
> You have confirmed that the blob-target fails to initialize probably in an other environment, without first having performed a manual config-reload after having setup the configuration correctly.
> 
> Think you have to figure yourself why the other environment is not working. Maybe make a custom build of the blob-target with extra debug logging.
> 
> If you can point to an issue in the blob-target source-code that needs to be improved, then please create a pull-request.
> 
> Btw. since you are not seeing any errors, then I guess that either you are looking for the output in the wrong container/environment, or that nothing is being written.

Everything works for me if i put the correct setting in appsettings.json everything is fine, but if the settings are in azure application settings, It stops working.

I did for fun now a test with the reload and wrong settings so my settings in appsettings.json are now
```
  "Storage": {
    "StorageConnectionString": "wrongConnectionString",
    "ContainerName": "wrongContainer",
```

and in azure
```
Storage.ContainerName | correctContainer
Storage.StorageConnectionString | correctConnectionString
```

So the expected behavior is that we have now after reload an error message because this is not a real Blob. Cutout from my logs:
```
2019/03/27 09:26:17.786|INFO |Program                       | Starting application...
2019/03/27 09:26:17.911|INFO |Program                       | correctContainer
2019/03/27 09:26:17.924|INFO |Program                       | correctConnectionString
```

But this not happens. There is no error message. So i don't think that BlobStorageTarget is loading correct after calling Log.LogManager.Configuration.Reload();

[console-nlog-internal (4).log](https://github.com/JDetmar/NLog.Extensions.AzureStorage/files/3012498/console-nlog-internal.4.log)

**Comment by snakefoot** [comment]
Did you try making a custom build that performs some more logging to the internal logger?


Again if you can point to where the chain pops off then it is much easier to fix


Sent from my Sony Xperia


---- oIllenseer wrote ----


Your trust in random people solving your environment problems is admirable.

You have confirmed that the blob-target is working for you in one environment.

You have confirmed that the blob-target fails to initialize probably in an other environment, without first having performed a manual config-reload after having setup the configuration correctly.

Think you have to figure yourself why the other environment is not working. Maybe make a custom build of the blob-target with extra debug logging.

If you can point to an issue in the blob-target source-code that needs to be improved, then please create a pull-request.

Btw. since you are not seeing any errors, then I guess that either you are looking for the output in the wrong container/environment, or that nothing is being written.

Everything works for me if i put the correct setting in appsettings.json everything is fine, but if the settings are in azure application settings, It stops working.

I did for fun now a test with the reload and wrong settings so my settings in appsettings.json are now

  "Storage": {
    "StorageConnectionString": "wrongConnectionString",
    "ContainerName": "wrongContainer",


and in azure

Storage.ContainerName | correctContainer
Storage.StorageConnectionString | correctConnectionString


So the expected behavior is that we have now after reload an error message because this is not a real Blob. Cutout from my logs:

2019/03/27 09:26:17.786|INFO |Program                       | Starting application...
2019/03/27 09:26:17.911|INFO |Program                       | correctContainer
2019/03/27 09:26:17.924|INFO |Program                       | correctConnectionString


But this not happens. There is no error message. So i don't think that BlobStorageTarget is loading correct after calling Log.LogManager.Configuration.Reload();

console-nlog-internal (4).log<https://github.com/JDetmar/NLog.Extensions.AzureStorage/files/3012498/console-nlog-internal.4.log>

**Comment by snakefoot** [comment]
@oIllenseer I have created a wiki-page that describes how to initialize NLog-config:

https://github.com/NLog/NLog/wiki/Dependency-injection-with-NLog#initialize-nlog-configuration
