### ISSUE TITLE
412 response status errors

### ISSUE THREAD

**Issue by ckouroupis** [JDetmar/NLog.Extensions.AzureStorage#56]
From Application Insights we are noticing a large volume of 412 response status errors. 

According to this article, AppendFromByteArray does not handle concurrency and it is recommended to use AppendBlock/AppendBlockAsync.

https://thuru.net/2015/11/29/the-remote-server-returned-an-error-412-the-append-position-condition-specified-was-not-met-azure-append-blob-issue/

**Comment by snakefoot** [comment]
NLog BlobStorageTarget puts a great effort into only having a single `AppendFromByteArrayAsync`-call active at a time.

But I can understand that it reaches UploadFromStreamAsyncHelper:

https://github.com/Azure/azure-storage-net/blob/bbb7da62bc49ee79e07cf607d2202c9778b83d56/Lib/WindowsRuntime/Blob/CloudAppendBlob.cs#L795

But I see no reason for allocating a MemoryStream for each call since right now it allocates a byte-array for each call. And MemoryStream is just a wrapper around a byte-array (one more allocation down the drain).

Will make a PR for you after dinner :)

**Comment by snakefoot** [comment]
Created  #57 for you

**Comment by snakefoot** [comment]
Nuget-package is ready for you here:

https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/29212806/artifacts

**Comment by ckouroupis** [comment]
@snakefoot, I have applied the Nuget package you provided. Tested it. All is working well and 412 errors are gone.
Thanks very, very much!!!

**Comment by snakefoot** [comment]
Updated nuget-package is now available:

https://www.nuget.org/packages/NLog.Extensions.AzureBlobStorage/
